# Generated by Django 3.2.16 on 2022-12-15 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='speed',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
