# Generated by Django 3.2.16 on 2022-12-15 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0004_auto_20221215_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='total',
        ),
    ]
